name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        step: [examples, test]
        optimize: [Debug, ReleaseSafe, ReleaseFast]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: mlugg/setup-zig@v1
      - run: zig build ${{ matrix.step }} -Doptimize=${{ matrix.optimize }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: zig fmt --check .
